### ISSUE TITLE
Hugo Catalogs page layout is broken - sidebar appearing at bottom of page

### ISSUE THREAD

**Issue by jputrino** [nginxinc/nginx-hugo-theme#61]
The table of contents (TOC) for the NMS Dimensions, Metrics, and Events catalogs is currently displaying at the bottom of the pages, not on the right side where it should appear.

https://docs.nginx.com/nginx-management-suite/reference/catalogs/dimensions/ 

https://docs.nginx.com/nginx-management-suite/reference/catalogs/metrics/ 

https://docs.nginx.com/nginx-management-suite/reference/catalogs/events/

https://github.com/nginxinc/nginx-hugo-theme/assets/12143793/7bc4abb4-0bab-4963-b68b-119f968c2f52

This may be a regression related to the recent page width issues. The catalogs layout is in the docs repo here: https://github.com/nginxinc/docs/blob/main/layouts/catalogs/single.html

**Comment by jputrino** [comment]
@LukeBillington to work with @Jcahilltorre on this

**Comment by nginx-jack** [comment]
Fixed deployed to production with updated hugo theme .0.41.8
